export const goldRing = [
  { title: "22gm", src: "/assets/items/ring/rings (1).jpeg" },
  { title: "10gm", src: "/assets/items/ring/rings (2).jpeg" },
  { title: "7gm", src: "/assets/items/ring/rings (3).jpeg" },
  { title: "13gm", src: "/assets/items/ring/rings (4).jpeg" },
  { title: "9gm", src: "/assets/items/ring/rings (5).jpeg" },
  { title: "14gm", src: "/assets/items/ring/rings (6).jpeg" },
  { title: "11gm", src: "/assets/items/ring/rings (7).jpeg" },
  { title: "8gm", src: "/assets/items/ring/rings (8).jpeg" },
  { title: "6gm", src: "/assets/items/ring/rings (9).jpeg" },
  { title: "12gm", src: "/assets/items/ring/rings (10).jpeg" },
  { title: "15gm", src: "/assets/items/ring/rings (11).jpeg" },
  { title: "5gm", src: "/assets/items/ring/rings (12).jpeg" },
  { title: "13gm", src: "/assets/items/ring/rings (13).jpeg" },
  { title: "10gm", src: "/assets/items/ring/rings (14).jpeg" },
  { title: "9gm", src: "/assets/items/ring/rings (15).jpeg" },
  { title: "14gm", src: "/assets/items/ring/rings (16).jpeg" },
  { title: "6gm", src: "/assets/items/ring/rings (17).jpeg" },
  { title: "11gm", src: "/assets/items/ring/rings (18).jpeg" },
  { title: "7gm", src: "/assets/items/ring/rings (19).jpeg" },
  { title: "8gm", src: "/assets/items/ring/rings (20).jpeg" },
  { title: "12gm", src: "/assets/items/ring/rings (21).jpeg" },
  { title: "5gm", src: "/assets/items/ring/rings (22).jpeg" },
  { title: "15gm", src: "/assets/items/ring/rings (23).jpeg" },
  { title: "10gm", src: "/assets/items/ring/rings (24).jpeg" },
  { title: "13gm", src: "/assets/items/ring/rings (25).jpeg" },
  { title: "9gm", src: "/assets/items/ring/rings (26).jpeg" },
  { title: "7gm", src: "/assets/items/ring/rings (27).jpeg" },
  { title: "14gm", src: "/assets/items/ring/rings (28).jpeg" },
  { title: "6gm", src: "/assets/items/ring/rings (29).jpeg" },
  { title: "11gm", src: "/assets/items/ring/rings (30).jpeg" },
  { title: "8gm", src: "/assets/items/ring/rings (31).jpeg" },
  { title: "12gm", src: "/assets/items/ring/rings (32).jpeg" },
  { title: "5gm", src: "/assets/items/ring/rings (33).jpeg" },
  { title: "15gm", src: "/assets/items/ring/rings (34).jpeg" },
  { title: "9gm", src: "/assets/items/ring/rings (35).jpeg" },
  { title: "13gm", src: "/assets/items/ring/rings (36).jpeg" },
  { title: "7gm", src: "/assets/items/ring/rings (37).jpeg" },
  { title: "14gm", src: "/assets/items/ring/rings (38).jpeg" },
  { title: "10gm", src: "/assets/items/ring/rings (39).jpeg" },
];

export const goldBracelet = [
  { title: "5.2gm", src: "/assets/items/bracelet/br1.jpeg" },
  { title: "6.3gm", src: "/assets/items/bracelet/br2.jpeg" },
  { title: "7.1gm", src: "/assets/items/bracelet/br3.jpeg" },
  { title: "8.8gm", src: "/assets/items/bracelet/br4.jpeg" },
  { title: "10.2gm", src: "/assets/items/bracelet/br6.jpeg" },
  { title: "11.7gm", src: "/assets/items/bracelet/br7.jpeg" },
  { title: "13.4gm", src: "/assets/items/bracelet/br9.jpeg" },
  { title: "7.5gm", src: "/assets/items/bracelet/br10.jpeg" },
  { title: "8.6gm", src: "/assets/items/bracelet/br11.jpeg" },
  { title: "9.9gm", src: "/assets/items/bracelet/br12.jpeg" },
  { title: "6.4gm", src: "/assets/items/bracelet/br14.jpeg" },
  { title: "5.7gm", src: "/assets/items/bracelet/br15.jpeg" },
  { title: "7.2gm", src: "/assets/items/bracelet/br16.jpeg" },
  { title: "12.3gm", src: "/assets/items/bracelet/br17.jpeg" },
  { title: "13.9gm", src: "/assets/items/bracelet/br18.jpeg" },
  { title: "14.1gm", src: "/assets/items/bracelet/br19.jpeg" },
  { title: "9.2gm", src: "/assets/items/bracelet/br20.jpeg" },
  { title: "10.6gm", src: "/assets/items/bracelet/br21.jpeg" },
  { title: "8.3gm", src: "/assets/items/bracelet/br22.jpeg" },
  { title: "11.1gm", src: "/assets/items/bracelet/br23.jpeg" },
  { title: "7.8gm", src: "/assets/items/bracelet/br24.jpeg" },
  { title: "14.6gm", src: "/assets/items/bracelet/br25.jpeg" },
  { title: "6.7gm", src: "/assets/items/bracelet/br26.jpeg" },
  { title: "10.4gm", src: "/assets/items/bracelet/br27.jpeg" },
];

export const goldChain = [
  { title: "22gm", src: "/assets/items/chain/chains (21).jpeg" },
  { title: "11gm", src: "/assets/items/chain/chains (22).jpeg" },
  { title: "24gm", src: "/assets/items/chain/chains (23).jpeg" },
  { title: "13gm", src: "/assets/items/chain/chains (24).jpeg" },
  { title: "20gm", src: "/assets/items/chain/chains (25).jpeg" },
  { title: "10gm", src: "/assets/items/chain/chains (26).jpeg" },
  { title: "18gm", src: "/assets/items/chain/chains (27).jpeg" },
  { title: "21gm", src: "/assets/items/chain/chains (28).jpeg" },
  { title: "17gm", src: "/assets/items/chain/chains (29).jpeg" },
  { title: "12gm", src: "/assets/items/chain/chain1.jpg" },
  { title: "15gm", src: "/assets/items/chain/chain2.jpg" },
  { title: "23gm", src: "/assets/items/chain/chain3.jpg" },
  { title: "11gm", src: "/assets/items/chain/chain4.jpg" },
  { title: "14gm", src: "/assets/items/chain/chain7.jpg" },
  { title: "19gm", src: "/assets/items/chain/chain8.jpg" },
  { title: "13gm", src: "/assets/items/chain/chain9.jpg" },
  { title: "20gm", src: "/assets/items/chain/chain13.jpg" },
  { title: "15gm", src: "/assets/items/chain/chain18.jpg" },
  { title: "23gm", src: "/assets/items/chain/chain19.jpg" },
  { title: "13gm", src: "/assets/items/chain/chain20.jpg" },
  { title: "12gm", src: "/assets/items/chain/chains (1).jpeg" },
  { title: "19gm", src: "/assets/items/chain/chains (2).jpeg" },
  { title: "15gm", src: "/assets/items/chain/chains (3).jpeg" },
  { title: "22gm", src: "/assets/items/chain/chains (4).jpeg" },
  { title: "11gm", src: "/assets/items/chain/chains (5).jpeg" },
  { title: "24gm", src: "/assets/items/chain/chains (6).jpeg" },
  { title: "14gm", src: "/assets/items/chain/chains (7).jpeg" },
  { title: "18gm", src: "/assets/items/chain/chains (8).jpeg" },
  { title: "21gm", src: "/assets/items/chain/chains (9).jpeg" },
  { title: "16gm", src: "/assets/items/chain/chains (10).jpeg" },
  { title: "23gm", src: "/assets/items/chain/chains (11).jpeg" },
  { title: "13gm", src: "/assets/items/chain/chains (12).jpeg" },
  { title: "20gm", src: "/assets/items/chain/chains (13).jpeg" },
  { title: "10gm", src: "/assets/items/chain/chains (14).jpeg" },
  { title: "17gm", src: "/assets/items/chain/chains (15).jpeg" },
  { title: "25gm", src: "/assets/items/chain/chains (16).jpeg" },
  { title: "15gm", src: "/assets/items/chain/chains (17).jpeg" },
  { title: "12gm", src: "/assets/items/chain/chains (18).jpeg" },
  { title: "19gm", src: "/assets/items/chain/chains (19).jpeg" },
  { title: "14gm", src: "/assets/items/chain/chains (20).jpeg" },
];

export const goldNecklace = [
  { title: "22gm", src: "/assets/items/necklace/necklace1.jpg" },
  { title: "17gm", src: "/assets/items/necklace/necklace2.jpeg" },
  { title: "29gm", src: "/assets/items/necklace/necklace3.jpeg" },
  { title: "21gm", src: "/assets/items/necklace/necklace4.jpeg" },
  { title: "18gm", src: "/assets/items/necklace/necklace5.jpeg" },
  { title: "26gm", src: "/assets/items/necklace/necklace6.jpeg" },
  { title: "15gm", src: "/assets/items/necklace/necklace7.jpeg" },
  { title: "24gm", src: "/assets/items/necklace/necklace8.jpeg" },
  { title: "30gm", src: "/assets/items/necklace/necklace9.jpeg" },
  { title: "16gm", src: "/assets/items/necklace/necklace10.jpeg" },
  { title: "27gm", src: "/assets/items/necklace/necklace11.jpeg" },
  { title: "19gm", src: "/assets/items/necklace/necklace12.jpeg" },
  { title: "23gm", src: "/assets/items/necklace/necklace13.jpeg" },
  { title: "20gm", src: "/assets/items/necklace/necklace14.jpeg" },
  { title: "28gm", src: "/assets/items/necklace/necklace15.jpeg" },
  { title: "25gm", src: "/assets/items/necklace/necklace16.jpeg" },
  { title: "18gm", src: "/assets/items/necklace/necklace17.jpeg" },
  { title: "30gm", src: "/assets/items/necklace/necklace18.jpeg" },
  { title: "22gm", src: "/assets/items/necklace/necklace19.jpeg" },
  { title: "16gm", src: "/assets/items/necklace/necklace20.jpeg" },
  { title: "27gm", src: "/assets/items/necklace/necklace21.jpeg" },
  { title: "21gm", src: "/assets/items/necklace/necklace22.jpeg" },
  { title: "25gm", src: "/assets/items/necklace/necklace23.jpeg" },
  { title: "19gm", src: "/assets/items/necklace/necklace24.jpeg" },
  { title: "28gm", src: "/assets/items/necklace/necklace25.jpeg" },
  { title: "15gm", src: "/assets/items/necklace/necklace26.jpeg" },
  { title: "23gm", src: "/assets/items/necklace/necklace27.jpeg" },
  { title: "17gm", src: "/assets/items/necklace/necklace28.jpeg" },
  { title: "20gm", src: "/assets/items/necklace/necklace30.jpeg" },
  { title: "26gm", src: "/assets/items/necklace/necklace31.jpeg" },
  { title: "24gm", src: "/assets/items/necklace/necklace32.jpeg" },
  { title: "18gm", src: "/assets/items/necklace/necklace33.jpeg" },
  { title: "30gm", src: "/assets/items/necklace/necklace34.jpeg" },
  { title: "22gm", src: "/assets/items/necklace/necklace35.jpeg" },
  { title: "19gm", src: "/assets/items/necklace/Necklace1.jpeg" },
];

export const goldEarrings = [
  { title: "22gm", src: "/assets/items/earring/earring (1).jpeg" },
  { title: "18gm", src: "/assets/items/earring/earring (2).jpeg" },
  { title: "14gm", src: "/assets/items/earring/earring (3).jpeg" },
  { title: "11gm", src: "/assets/items/earring/earring (4).jpeg" },
  { title: "19gm", src: "/assets/items/earring/earring (5).jpeg" },
  { title: "16gm", src: "/assets/items/earring/earring (6).jpeg" },
  { title: "13gm", src: "/assets/items/earring/earring (7).jpeg" },
  { title: "15gm", src: "/assets/items/earring/earring (8).jpeg" },
  { title: "20gm", src: "/assets/items/earring/earring (9).jpeg" },
  { title: "12gm", src: "/assets/items/earring/earring (10).jpeg" },
  { title: "17gm", src: "/assets/items/earring/earring (11).jpeg" },
  { title: "10gm", src: "/assets/items/earring/earring (12).jpeg" },
  { title: "19gm", src: "/assets/items/earring/earring (13).jpeg" },
  { title: "14gm", src: "/assets/items/earring/earring (14).jpeg" },
  { title: "11gm", src: "/assets/items/earring/earring (15).jpeg" },
  { title: "18gm", src: "/assets/items/earring/earring (16).jpeg" },
  { title: "15gm", src: "/assets/items/earring/earring (17).jpeg" },
  { title: "13gm", src: "/assets/items/earring/earring (18).jpeg" },
  { title: "12gm", src: "/assets/items/earring/earring (19).jpeg" },
  { title: "16gm", src: "/assets/items/earring/earring (20).jpeg" },
  { title: "20gm", src: "/assets/items/earring/earring (21).jpeg" },
  { title: "10gm", src: "/assets/items/earring/earring (22).jpeg" },
  { title: "19gm", src: "/assets/items/earring/earring (23).jpeg" },
  { title: "11gm", src: "/assets/items/earring/earring (24).jpeg" },
  { title: "17gm", src: "/assets/items/earring/earring (25).jpeg" },
  { title: "14gm", src: "/assets/items/earring/earring (27).jpeg" },
  { title: "18gm", src: "/assets/items/earring/earring (28).jpeg" },
  { title: "12gm", src: "/assets/items/earring/earring (29).jpeg" },
  { title: "20gm", src: "/assets/items/earring/earring (30).jpeg" },
  { title: "15gm", src: "/assets/items/earring/earring (31).jpeg" },
  { title: "10gm", src: "/assets/items/earring/earring (32).jpeg" },
  { title: "19gm", src: "/assets/items/earring/earring (33).jpeg" },
  { title: "16gm", src: "/assets/items/earring/earring (34).jpeg" },
  { title: "13gm", src: "/assets/items/earring/earring (35).jpeg" },
  { title: "11gm", src: "/assets/items/earring/earring (36).jpeg" },
  { title: "14gm", src: "/assets/items/earring/earring (37).jpeg" },
  { title: "18gm", src: "/assets/items/earring/earring (38).jpeg" },
  { title: "17gm", src: "/assets/items/earring/earring (39).jpeg" },
  { title: "12gm", src: "/assets/items/earring/earring (40).jpeg" },
  { title: "20gm", src: "/assets/items/earring/earring (41).jpeg" },
  { title: "10gm", src: "/assets/items/earring/earring (42).jpeg" },
  { title: "15gm", src: "/assets/items/earring/earring (43).jpeg" },
  { title: "19gm", src: "/assets/items/earring/earring (44).jpeg" },
];

export const goldNoseRings = [
  { title: "22gm", src: "/assets/items/nosering/nosering (1).jpeg" },
  { title: "12gm", src: "/assets/items/nosering/nosering (2).jpeg" },
  { title: "17gm", src: "/assets/items/nosering/nosering (3).jpeg" },
  { title: "15gm", src: "/assets/items/nosering/nosering (4).jpeg" },
  { title: "18gm", src: "/assets/items/nosering/nosering (5).jpeg" },
  { title: "13gm", src: "/assets/items/nosering/nosering (6).jpeg" },
  { title: "11gm", src: "/assets/items/nosering/nosering (7).jpeg" },
  { title: "19gm", src: "/assets/items/nosering/nosering (8).jpeg" },
  { title: "10gm", src: "/assets/items/nosering/nosering (9).jpeg" },
  { title: "16gm", src: "/assets/items/nosering/nosering (10).jpeg" },
  { title: "14gm", src: "/assets/items/nosering/nosering (11).jpeg" },
  { title: "20gm", src: "/assets/items/nosering/nosering (12).jpeg" },
  { title: "12gm", src: "/assets/items/nosering/nosering (13).jpeg" },
  { title: "17gm", src: "/assets/items/nosering/nosering (14).jpeg" },
  { title: "13gm", src: "/assets/items/nosering/nosering (15).jpeg" },
  { title: "18gm", src: "/assets/items/nosering/nosering (16).jpeg" },
  { title: "11gm", src: "/assets/items/nosering/nosering (17).jpeg" },
  { title: "15gm", src: "/assets/items/nosering/nosering (18).jpeg" },
  { title: "19gm", src: "/assets/items/nosering/nosering (19).jpeg" },
  { title: "14gm", src: "/assets/items/nosering/nosering (20).jpeg" },
  { title: "10gm", src: "/assets/items/nosering/nosering (21).jpeg" },
  { title: "16gm", src: "/assets/items/nosering/nosering (22).jpeg" },
  { title: "20gm", src: "/assets/items/nosering/nosering (23).jpeg" },
  { title: "12gm", src: "/assets/items/nosering/nosering (24).jpeg" },
  { title: "18gm", src: "/assets/items/nosering/nosering (25).jpeg" },
  { title: "13gm", src: "/assets/items/nosering/nosering (26).jpeg" },
  { title: "17gm", src: "/assets/items/nosering/nosering (27).jpeg" },
  { title: "15gm", src: "/assets/items/nosering/nosering (28).jpeg" },
  { title: "11gm", src: "/assets/items/nosering/nosering (29).jpeg" },
  { title: "19gm", src: "/assets/items/nosering/nosering (30).jpeg" },
  { title: "14gm", src: "/assets/items/nosering/nosering (31).jpeg" },
  { title: "10gm", src: "/assets/items/nosering/nosering (32).jpeg" },
];

export const goldMangalsutra = [
  { title: "22gm", src: "/assets/items/mangalsutra/mangalsutra (1).jpeg" },
  { title: "15gm", src: "/assets/items/mangalsutra/mangalsutra (2).jpeg" },
  { title: "20gm", src: "/assets/items/mangalsutra/mangalsutra (3).jpeg" },
  { title: "11gm", src: "/assets/items/mangalsutra/mangalsutra (4).jpeg" },
  { title: "18gm", src: "/assets/items/mangalsutra/mangalsutra (5).jpeg" },
  { title: "24gm", src: "/assets/items/mangalsutra/mangalsutra (6).jpeg" },
  { title: "14gm", src: "/assets/items/mangalsutra/mangalsutra (7).jpeg" },
  { title: "23gm", src: "/assets/items/mangalsutra/mangalsutra (8).jpeg" },
  { title: "12gm", src: "/assets/items/mangalsutra/mangalsutra (9).jpeg" },
  { title: "19gm", src: "/assets/items/mangalsutra/mangalsutra (10).jpeg" },
  { title: "16gm", src: "/assets/items/mangalsutra/mangalsutra (11).jpeg" },
  { title: "25gm", src: "/assets/items/mangalsutra/mangalsutra (12).jpeg" },
  { title: "13gm", src: "/assets/items/mangalsutra/mangalsutra (13).jpeg" },
  { title: "21gm", src: "/assets/items/mangalsutra/mangalsutra (14).jpeg" },
  { title: "17gm", src: "/assets/items/mangalsutra/mangalsutra (15).jpeg" },
  { title: "10gm", src: "/assets/items/mangalsutra/mangalsutra (16).jpeg" },
  { title: "15gm", src: "/assets/items/mangalsutra/mangalsutra (18).jpeg" },
  { title: "24gm", src: "/assets/items/mangalsutra/mangalsutra (19).jpeg" },
  { title: "18gm", src: "/assets/items/mangalsutra/mangalsutra (20).jpeg" },
  { title: "11gm", src: "/assets/items/mangalsutra/mangalsutra (21).jpeg" },
  { title: "19gm", src: "/assets/items/mangalsutra/mangalsutra (22).jpeg" },
  { title: "14gm", src: "/assets/items/mangalsutra/mangalsutra (23).jpeg" },
  { title: "23gm", src: "/assets/items/mangalsutra/mangalsutra (24).jpeg" },
  { title: "12gm", src: "/assets/items/mangalsutra/mangalsutra (25).jpeg" },
  { title: "20gm", src: "/assets/items/mangalsutra/mangalsutra (26).jpeg" },
  { title: "16gm", src: "/assets/items/mangalsutra/mangalsutra (27).jpeg" },
  { title: "25gm", src: "/assets/items/mangalsutra/mangalsutra (28).jpeg" },
  { title: "13gm", src: "/assets/items/mangalsutra/mangalsutra (29).jpeg" },
  { title: "21gm", src: "/assets/items/mangalsutra/mangalsutra (30).jpeg" },
  { title: "17gm", src: "/assets/items/mangalsutra/mangalsutra (31).jpeg" },
];

export const diamondRing = [
  { title: "25% off mkc", src: "/assets/items/dring/dring (1).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (2).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (3).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (4).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (5).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (6).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (7).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (8).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (9).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (10).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (11).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (12).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (13).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (14).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (15).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (16).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (17).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (18).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (19).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (20).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (21).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (22).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (23).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (24).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (25).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (26).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (27).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (28).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (29).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (30).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (31).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (32).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (33).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (34).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (35).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (36).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (37).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (38).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (39).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (40).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dring/dring (41).jpeg" },
];

export const diamondNecklace = [
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (1).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (2).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (3).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (4).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (5).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (6).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (7).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (8).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (9).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (10).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (11).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (12).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (13).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (14).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (15).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (16).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (17).jpeg" },
  { title: "25% off mkc", src: "/assets/items/dnecklace/dnecklace (18).jpeg" },
];
